### ISSUE TITLE
Measuring performance details

### ISSUE THREAD

**Issue by mindplay-dk** [krausest/js-framework-benchmark#650] opened 2019-10-18 06:51 UTC
Time-slicing (fiber-based render-scheduling) will likely be introduced in React in the near future.

I have been helping out with a React-alternative myself for a couple of weeks now, which will also feature non-blocking render-scheduling, and I believe we are likely to see more libraries like this in the future.

How do we benchmark the performance of these libraries?

Merely measuring time taken seems like it's going to favor frameworks without this feature - which seems unfair, given that this is a feature designed to improve perceived performance, e.g. by unblocking the UI thread for long enough to keep CSS animations running smoothly while rendering many slow components.

Two ideas:

1. Measure actual CPU usage while running the tests - most conventional frameworks will be at 100% on the CPU core running the JS main thread, while frameworks that implement time-slicing should be giving some time back. (This can't be measured from JS, so it may be difficult to implement in practice. Presenting this data in a meaningful way may also be challenging.)

2. Measure maximum blocking durations - most conventional frameworks, for example, will block for the entire duration of rendering a large table, while frameworks that implement time-slicing will block only for as long as the slowest component instance takes to render. (This should be measurable using plain JS, e.g. by scheduling measurements with `performance.now` from a `setInterval` callback or something similar.)

Thoughts?

**Comment by ryansolid** [comment] 2019-10-18 07:39
I am not likely as familiar with Fiber but I am with writing implementations for this benchmark.

Isn't the problem is it is sort of both ways. They are implementing this to improve perceived performance, so one could argue it is just as unfair to measure a library doing less work etc. I think it's going to be difficult in this sort of benchmark to capture that. Like in a real-world situation with 10k rows you'd be windowing and only drawing the rows that are within range of the visible part of the client, it would improve the loading and scrolling performance but it isn't equivalent to loading all the rows. 

Similarly, anyone could add a `requestIdleCallback` to their rendering scheduling to improve perceived loading even if the overall time is longer. There is a whole scale of different variations of these sorts of techniques right down to the old fade in the data. Opting into using them can be better for the end-user but I suspect there isn't a correlation between perceptual improvements of varying techniques and performance characteristics measured. As in the best experience might not be the one that wins along any particular axis. I was playing with Sierpinski's Triangle Demo that was first shown when Fiber was announced and I found I could get what I considered better experience than what the stock React had by using more complicated scheduling than simply using `requestIdleCallback` as in an underpowered device the numbers in the circles would never update.  Was React blocking less, yes. But was it the right answer in that situation? Maybe not.

So I suspect uniformity is going to be the problem. There are several libraries here on a core i5 or weaker that can render 10k rows at least twice as fast as React does so likely no amount of perceived performance will match that in a measurable way I suspect. I think animation demos are probably the domain of this sort of feature. Like the Sierpinski Triangle, or the old Circles Benchmark. Ones where people can visualize the experience.

**Comment by 132yse** [comment] 2019-10-18 10:08
I agree, if the performance test is for synchronous framework, it is unfair for asynchronous framework.

But it is difficult to implement it. Before that, my request is to remind that asynchronous rendering framework (such as react, FRE)

**Comment by mindplay-dk** [comment] 2019-10-18 10:28
I don't think I'm looking for a way to "level the playing field", so much as merely adding more details to the benchmark - additional data that can help people choose based on their own wishes or needs.

Maybe you do want to compare solely on "time to render", and that's fair - libraries using time slicing will most likely come out bottom.

But maybe you also care about "net CPU load while rendering", where synchronous libraries will come in at 100%, async libraries with some form of render queue/scheduling might come in a little lower, and libraries with time-slicing maybe the same or a little lower than that.

If your project is animation-heavy (games, etc.) you might care about "UI thread blocked", perhaps in milliseconds (average or max) which might tell you something about potential performance of the library in such scenarios.

So I'm not looking for a way to pit synchronous vs asynchronous vs time-sliced libraries against each other - I'm more thinking along the lines of, how do we compare these new time-sliced libraries against each other?

Their approach to scheduling is going to differ - their overall DOM update performance is obviously going to differ. So you're not really going to be able to compare them with the metrics we have available now, since "time taken" isn't going to be the only (or most) meaningful difference between those libraries.

**Comment by 132yse** [comment] 2019-10-18 10:40
> how do we compare these new time-sliced libraries against each other.

I respectfully disagree, different frameworks for asynchronous rendering may not be necessary for comparison.

Because time is free to slice, there is no good or bad way. We just need to reach a balance state, and then the UI will not be blocked.

There is no indicator to show whether it is good or not. Because of different FPS, it is enough to achieve a utilization rate of 50 frames on a device with 60 FPS.

**Comment by localvoid** [comment] 2019-10-18 11:58
> I'm more thinking along the lines of, how do we compare these new time-sliced libraries against each other?

First of all, you'll need to figure out what type of real-world use cases will benefit from time slicing, not some weird artificial loops like in Sierpinski demo.

**Comment by 132yse** [comment] 2019-11-27 04:45
@mindplay-dk @ryansolid @localvoid Here is a new proposal that mentions some new performance testing.
Such as total-blocking-time, which is useful for react or fre.
We can't just rely on testing the total rendering time to judge the performance. The total blocking time is a good way.

https://wicg.github.io/largest-contentful-paint

**Comment by ryansolid** [comment] 2019-11-27 06:56
I suppose, but isn't this still down to scenario? Maybe Im not understanding this properly. All these libraries which have the ability to block less (hardly limited to libraries like React), could do so at the cost of rendering performance. But why? This now can be measured lets say, but what amount of blocking is just right? At what point is largest contentful paint worth more than the screen being rendered quicker ?

**Comment by 132yse** [comment] 2019-11-27 07:22
> but what amount of blocking is just right?

As little as possible, of course

> At what point is largest contentful paint worth more than the screen being rendered quicker ?

The larger the amount of data, the more valuable it is. For example, in the current test case, `add 10000 rows`, the button will be blocked.

**Comment by ryansolid** [comment] 2019-11-27 08:07
> As little as possible, of course
Is it though? At what cost? 20% reduction in render performance? 40%?

> The larger the amount of data, the more valuable it is. For example, in the current test case, add 10000 rows, the button will be blocked.

Sure but if you have no intention of interacting with the button. Like it would have been greyed out anyway, wouldn't you prefer faster loading times. Isnt that also where the gap in performance would be largest.

I guess I'm having a hard time seeing an absolute here. Dont get me wrong. This is a great feature to handle expensive interaction for top down reconciled libraries where it is not so trivial to split workflows.

Like let's say I'm using React Concurrent Mode I still have power over how I split up my workflow. So what makes one better than the other? It blocks less? Renders faster? The perfect middle ground? How do I with even React alone know the right implementation?

**Comment by 132yse** [comment] 2019-11-27 08:12
>  It blocks less? Renders faster? The perfect middle ground? 

I think this is what users care about

To be fair, the test only needs to give the blocking time and rendering time, and how to balance the two should be given to the user

In fact, there is no absolute standard, but in different scenarios, the demand for two indicators is different.


For example, some animations, visualizations, large amounts of data, users can choose a framework with short blocking time

**Comment by mindplay-dk** [comment] 2019-11-27 11:51
> > > but what amount of blocking is just right?
> >
> > As little as possible, of course
> 
> Is it though? At what cost? 20% reduction in render performance? 40%?

I see your point, but render performance overhead isn't a fixed percentage.

In my optic, the ideal amount of blocking is "enough to keep the page responsive" - up to a limit, of course, where diverting too much time to other tasks makes the net render time unacceptable. (which *could* be a fixed percentage.)

Ideally, this shouldn't come at any cost in render performance - I realize it's impossible to implement render scheduling without adding some overhead, but optimally, the engine should give back *just* enough time to keep scrolling and CSS animations etc. running smoothly while updating components.

If there is no scrolling or CSS animations currently taking up any time on the main thread, ideally, render performance shouldn't be impacted substantially compared with a blocking renderer.

In other words, during rendering, the optimal non-blocking renderer will spend as much of the available CPU time as possible, minus the time required to keep scrolling and animations running at a responsive frame rate. (Of course, it's up to the framework authors how many FPS they think are required to keep things feeling "responsive", the maximum time they allow for those real-time updates during a long render, and so on.)

So I do think total blocking time (while being a completely meaningless metric for blocking renderers) might be a useful metric to compare e.g. React and Fre - the main reason you'd use a non-blocking renderer in the first place, is to keep things feeling responsive, even during large updates, so, while this may not make sense as a *stand-alone* metric, it should tell you something when you hold it up against the net rendering time, right?

It should give you some idea as to *what* you're comparing.

**Comment by krausest** [comment] 2020-12-13 20:41
I'm closing older issues that won't get fixed.

**Closed by krausest** 2020-12-13 20:41 UTC
