### ISSUE TITLE
Failure postinstall npm dependencies

### ISSUE THREAD

**Issue by diervo** [krausest/js-framework-benchmark#43] opened 2016-08-27 18:04 UTC
Is probably not an issue related to this repo on its own, but most likely you guys can let the aurelia owners know that their package seems to be broken:

```
node v6.2.1
npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! js-framework-benchmark-aurelia@1.0.0 postinstall: `jspm install -y`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js-framework-benchmark-aurelia@1.0.0 postinstall script 'jspm install -y'.
```

**Comment by krausest** [comment] 2016-08-30 18:45
Sorry, can't reproduce this problem. Here's my output from npm install in aurelia-v1.0.0-rc1.0.0. Can you please try again?

```
npm install
npm WARN deprecated babel@6.5.2: Babel's CLI commands have been moved from the babel package to the babel-cli package
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

> js-framework-benchmark-aurelia@1.0.0 postinstall /Users/stefan/Source/Javascript/js-framework-benchmark/aurelia-v1.0.0-rc1.0.0
> jspm install -y

     Looking up npm:babel-core
     Looking up npm:babel-runtime
     Looking up npm:aurelia-animator-css
     Looking up npm:core-js

warn Using local override for npm:core-js@1.2.6
     Looking up npm:aurelia-bootstrapper
     Looking up npm:aurelia-loader-default
     Looking up npm:aurelia-history-browser
     Looking up npm:aurelia-framework
     Looking up npm:aurelia-templating-binding
     Looking up npm:aurelia-fetch-client
     Looking up npm:aurelia-templating-resources
     Looking up npm:aurelia-logging-console
     Looking up npm:aurelia-router
     Looking up npm:aurelia-templating-router
     Updating registry cache...
     Looking up github:github/fetch
     Looking up github:systemjs/plugin-text
     Looking up github:twbs/bootstrap
ok   Up to date - aurelia-fetch-client as npm:aurelia-fetch-client@^1.0.0-rc.1.0.1 (1.0.0-rc.1.0.1)
ok   Up to date - fetch as github:github/fetch@^0.10.1 (0.10.1)
ok   Up to date - text as github:systemjs/plugin-text@^0.0.3 (0.0.3)
ok   Up to date - babel as npm:babel-core@^5.6.4 (5.8.38)
     Looking up npm:aurelia-metadata
     Looking up npm:aurelia-pal
     Looking up npm:aurelia-loader
     Looking up npm:aurelia-templating
     Looking up npm:aurelia-event-aggregator
     Looking up npm:aurelia-polyfills
     Looking up npm:aurelia-pal-browser
     Looking up npm:aurelia-history
     Looking up npm:aurelia-binding
     Looking up npm:aurelia-task-queue
     Looking up npm:aurelia-dependency-injection
     Looking up npm:aurelia-logging
     Looking up npm:aurelia-path
     Looking up npm:aurelia-route-recognizer
ok   Up to date - aurelia-history-browser as npm:aurelia-history-browser@^1.0.0-rc.1.0.0 (1.0.0-rc.1.0.0)
ok   Up to date - aurelia-logging-console as npm:aurelia-logging-console@^1.0.0-rc.1.0.0 (1.0.0-rc.1.0.0)
ok   Up to date - aurelia-loader-default as npm:aurelia-loader-default@^1.0.0-rc.1.0.0 (1.0.0-rc.1.0.0)
ok   Up to date - aurelia-router as npm:aurelia-router@^1.0.0-rc.1.0.1 (1.0.0-rc.1.0.1)
ok   Up to date - aurelia-framework as npm:aurelia-framework@^1.0.0-rc.1.0.2 (1.0.0-rc.1.0.2)
ok   Up to date - aurelia-templating-binding as npm:aurelia-templating-binding@^1.0.0-rc.1.0.1 (1.0.0-rc.1.0.1)
ok   Up to date - aurelia-templating-resources as npm:aurelia-templating-resources@^1.0.0-rc.1.0.1 (1.0.0-rc.1.0.1)
ok   Up to date - aurelia-bootstrapper as npm:aurelia-bootstrapper@^1.0.0-rc.1.0.1 (1.0.0-rc.1.0.1)
ok   Up to date - aurelia-animator-css as npm:aurelia-animator-css@^1.0.0-rc.1.0.0 (1.0.0-rc.1.0.0)
ok   Up to date - aurelia-templating-router as npm:aurelia-templating-router@^1.0.0-rc.1.0.1 (1.0.0-rc.1.0.1)
     Looking up github:jspm/nodelibs-path
     Looking up github:jspm/nodelibs-process
     Looking up github:jspm/nodelibs-fs
     Looking up github:systemjs/plugin-json
     Looking up npm:path-browserify
     Looking up npm:process
     Looking up npm:jquery
     Downloading npm:jquery@3.1.0
     Looking up github:jspm/nodelibs-vm
     Looking up github:jspm/nodelibs-assert
     Looking up npm:vm-browserify
     Looking up npm:assert
     Looking up npm:indexof
     Looking up npm:util
     Looking up npm:inherits
     Looking up github:jspm/nodelibs-buffer
     Looking up github:jspm/nodelibs-util
     Looking up npm:buffer
     Looking up npm:base64-js
     Looking up npm:isarray
     Looking up npm:ieee754
     Looking up github:jspm/nodelibs-child_process
ok   Up to date - core-js as npm:core-js@^1.2.6 (1.2.6)
ok   Up to date - babel-runtime as npm:babel-runtime@^5.6.4 (5.8.38)
ok   Installed npm:jquery (3.1.0)
ok   Up to date - bootstrap as github:twbs/bootstrap@^3.3.5 (3.3.6)
ok   Install tree has no forks.
     Looking up loader files...
       system.src.js
       system.js
       system-csp-production.src.js
       system-polyfills.js
       system.js.map
       system-polyfills.src.js
       system-polyfills.js.map
       system-csp-production.js
       system-csp-production.js.map

     Using loader versions:
       systemjs@0.19.37
ok   Loader files downloaded successfully

ok   Install complete.

**Comment by localvoid** [comment] 2016-09-02 03:11
Maybe just build all implementations and add them to repo, so there is no need to download all dev dependencies when someone tries to run all benchmarks.

**Comment by krausest** [comment] 2016-09-20 20:24
I'm closing this issue. The build just worked fine on a clean linux vm. But I really consider adding the dist directories and making npm install / building optional to save frustration on both sides.

**Closed by krausest** 2016-09-20 20:24 UTC
