### ISSUE TITLE
copy/paste selection doesn't appear to work

### ISSUE THREAD

**Issue by whittet** [krausest/js-framework-benchmark#1672] opened 2024-05-10 20:53 UTC
Copy/paste selection is confusing. Doesn't appear to help me store my selections for use in the future. I'm on the chrome 124 browser on a Chromebook. Same issue for current.html and today's release of Chrome 124 data. Best wishes!

**Comment by krausest** [comment] 2024-05-12 20:38
Sorry, I have no chromebook to check. Is it possible to open a console on a chromebook and see if there's some output?

**Comment by whittet** [comment] 2024-05-12 21:27
Hi, Steps from current.html:
1. change the list of frameworks
2. click the X
3. click copy button
4. Url changes to [this](https://krausest.github.io/js-framework-benchmark/current.html#eyJmcmFtZXdvcmtzIjpbImtleWVkL2FuZ3VsYXItY2Ytbm96b25lIiwia2V5ZWQvYW5ndWxhci1jZi1zaWduYWxzIiwia2V5ZWQvcmVhY3QtaG9va3MiLCJrZXllZC9zb2xpZCIsImtleWVkL3ZhbmlsbGFqcy0zIiwibm9uLWtleWVkL2FsaW5zIiwibm9uLWtleWVkL2FwcHJ1biIsIm5vbi1rZXllZC9hcnJvd2pzIiwibm9uLWtleWVkL2FydCIsIm5vbi1rZXllZC9hdXJlbGlhIiwibm9uLWtleWVkL2JhdSIsIm5vbi1rZXllZC9iaW5kaW5nLnNjYWxhIiwibm9uLWtleWVkL2J1aSIsIm5vbi1rZXllZC9jeWNsZWpzLWRvbSIsIm5vbi1rZXllZC9jeWRvbiIsIm5vbi1rZXllZC9kZWxlaWdodCIsIm5vbi1rZXllZC9kZWxvcmVhbiIsIm5vbi1rZXllZC9kbGlnaHRqcyIsIm5vbi1rZXllZC9kb3oiLCJub24ta2V5ZWQvZWYtanMiLCJub24ta2V5ZWQvZWxtIiwibm9uLWtleWVkL2Zhc3QiLCJub24ta2V5ZWQvZnJlaS1ob29rcyIsIm5vbi1rZXllZC9neXJvbiIsIm5vbi1rZXllZC9oYWxvZ2VuIiwibm9uLWtleWVkL2h5ZHJvLWpzIiwibm9uLWtleWVkL2ltYmEiLCJub24ta2V5ZWQvaW5jcl9kb20iLCJub24ta2V5ZWQvaW5mZXJubyIsIm5vbi1rZXllZC9rb2JvbGQiLCJub24ta2V5ZWQva29ydmluIiwibm9uLWtleWVkL2xlZ2VuZC1zdGF0ZS1vcHRpbWl6ZWQiLCJub24ta2V5ZWQvbGl0Iiwibm9uLWtleWVkL2xpdC1odG1sIiwibm9uLWtleWVkL2xpdGVyYWxqcyIsIm5vbi1rZXllZC9tYXF1ZXR0ZSIsIm5vbi1rZXllZC9taWthZG8iLCJub24ta2V5ZWQvbWltYmwiLCJub24ta2V5ZWQvbWlzbyIsIm5vbi1rZXllZC9tb2d3YWkiLCJub24ta2V5ZWQvbXV0cmFjdGlvbiIsIm5vbi1rZXllZC9vcGVudWk1Iiwibm9uLWtleWVkL3F1ZWwiLCJub24ta2V5ZWQvcmFjdGl2ZSIsIm5vbi1rZXllZC9yZWFjdC1jbGFzc2VzIiwibm9uLWtleWVkL3JlZG9tIiwibm9uLWtleWVkL3JlZmxleC1kb20iLCJub24ta2V5ZWQvcmVrZW4iLCJub24ta2V5ZWQvcmlvdCIsIm5vbi1rZXllZC9zYW4iLCJub24ta2V5ZWQvc2NhcmxldHMtZnJhbWUiLCJub24ta2V5ZWQvc2VlZCIsIm5vbi1rZXllZC9zbGltLWpzIiwibm9uLWtleWVkL3NsaW5nanMiLCJub24ta2V5ZWQvc3ByYWUiLCJub24ta2V5ZWQvc3Rkd2ViIiwibm9uLWtleWVkL3N0cnZlIiwibm9uLWtleWVkL3N2ZWx0ZS1jbGFzc2ljIiwibm9uLWtleWVkL3Vkb21zYXktZXN4Iiwibm9uLWtleWVkL3VodG1sIiwibm9uLWtleWVkL3VpNS13ZWJjb21wb25lbnRzIiwibm9uLWtleWVkL3ZhbmlsbGFqcyIsIm5vbi1rZXllZC92YW5pbGxhanMtMSIsIm5vbi1rZXllZC92b2J5Iiwibm9uLWtleWVkL3Z1ZSIsIm5vbi1rZXllZC92dWUtdmFwb3IiXSwiYmVuY2htYXJrcyI6WyIwMV9ydW4xayIsIjAyX3JlcGxhY2UxayIsIjAzX3VwZGF0ZTEwdGgxa194MTYiLCIwNF9zZWxlY3QxayIsIjA1X3N3YXAxayIsIjA2X3JlbW92ZS1vbmUtMWsiLCIwN19jcmVhdGUxMGsiLCIwOF9jcmVhdGUxay1hZnRlcjFrX3gyIiwiMDlfY2xlYXIxa194OCIsIjIxX3JlYWR5LW1lbW9yeSIsIjIyX3J1bi1tZW1vcnkiLCIyM191cGRhdGU1LW1lbW9yeSIsIjI1X3J1bi1jbGVhci1tZW1vcnkiLCIyNl9ydW4tMTBrLW1lbW9yeSIsIjQxX3NpemUtdW5jb21wcmVzc2VkIiwiNDJfc2l6ZS1jb21wcmVzc2VkIiwiNDNfZmlyc3QtcGFpbnQiXSwiZGlzcGxheU1vZGUiOjF9)
5. I bookmark this link and open in another tab. Then click the button and see this error in dev console:
index-gG23Mmdu.js:324 Pasting state failed SyntaxError: Unexpected token 'h', "https://kr"... is not valid JSON
    at JSON.parse (<anonymous>)
    at index-gG23Mmdu.js:324:428
    at index-gG23Mmdu.js:324:780

**Comment by krausest** [comment] 2024-12-14 19:31
I'm closing this issue. I'm not able to reproduce this (but I also have no chrome book to verify).

**Closed by krausest** 2024-12-14 19:31 UTC

**Comment by whittet** [comment] 2024-12-14 21:04
Any chance you tried it on Chrome?
Shane Whittet

**Comment by krausest** [comment] 2024-12-14 21:07
Yes, I tried it with chrome 131 on OSX.

**Comment by whittet** [comment] 2024-12-14 21:09
Where my listed steps the correct steps?

Shane Whittet

**Comment by whittet** [comment] 2024-12-14 23:14
Were my steps correct?
Shane Whittet

**Comment by krausest** [comment] 2024-12-15 10:02
I tried what you described, but it works on OSX.
However I'm trying to store the state in the URL and the URL has some platform specific limited length. So I can imagine that there's an issue.

Using the URL isn't a real use case for me. When I update some frameworks I have locally the new results and on github the last published results. To make a comparison I'm selecting the frameworks on the local results, then press the copy button to get the state in the clipboard.
On the github page I'm using the paste button to get the same frameworks selected from the clipboard. This shouldn't run into any length issues.

**Comment by krausest** [comment] 2024-12-15 15:08
What's your use case for doing so? I'm always coping and pasting the selection on different domains (localhost and github) such that localStorage wouldn't help me. I could store the selection in localStorage if that helps anyone...
