### ISSUE TITLE
Neverland build is broken

### ISSUE THREAD

**Issue by krausest** [krausest/js-framework-benchmark#708] opened 2020-03-15 21:33 UTC
Usually this is due to a version that isn't locked, but not in this case.
Both keyed and non-keyed version are broken when rebuilt.

@WebReflection Can you please take a look at it? I tried to downgrade  some packages that differed between the old package-lock.json and the current but didn't find the guilty one.

**Comment by WebReflection** [comment] 2020-03-15 23:09
I'm on it ... there are changes in latest lighterhtml that haven't landed officially in Neverland yet but breaks the logic there. I couldn't expect issues in here but I'll try to push an update that works, or maybe pin exact version in Neverland and push a patch so that this issue should be resolved until the latest land.
Apologies for the inconvenient, I didn't know tests here would run even when no version changes were requested via PR

**Comment by WebReflection** [comment] 2020-03-16 08:47
Neverland 3.3.0 just landed and it's being benchmarked without issues.
If you want I can file a pr with a newer package.json with all the updates. The failure was caused by a dependency that got updated too so let me know if you prefer a clear MR with pinned version or you just pin 3.3.0 and solve it, thanks.

P S. heresy got updated too, actually all my libraries did so I might as well file a pr with all changes at once

**Comment by WebReflection** [comment] 2020-03-16 11:24
I went ahead and created a PR to update them all, hoping I won't change much in the near future, as the refactoring has been already big enough.
https://github.com/krausest/js-framework-benchmark/pull/709

**Closed** 2020-03-22 20:59 UTC
