### ISSUE TITLE
add maquette

### ISSUE THREAD

**Issue by leeoniya** [krausest/js-framework-benchmark#270] opened 2017-11-01 18:59 UTC
hey @johan-gorter, now that maquette v3.0 is out, is there any interest in joining the party? :)

this bench is pretty easy to implement but if you dont have time, i can try to slap something together and you can tune it as needed.

https://github.com/AFASSoftware/maquette/issues/38

**Comment by johan-gorter** [comment] 2017-11-02 08:42
Sure we want to join this party. I currently do not have time to get much work done, but it should be enough to do the tuning. I already implemented the uibench benchmark, so you can find implementation clues [here](https://github.com/AFASSoftware/maquette/blob/51a291bb7c2bb8343417a3c46107edc72a86ba02/examples/benchmarks/uibench/app.ts#L142).

From my experience with uibench, I know that maquette is neither the fastest nor the slowest framework when it comes to pure DOM manipulation. It should be one of the fastest when there are no changes. We also want to build a [feature](https://github.com/AFASSoftware/maquette/issues/118) which allows you to minimize costly reflows when measuring DOM nodes.

**Comment by leeoniya** [comment] 2017-11-02 13:20
i made a keyed impl here: https://github.com/krausest/js-framework-benchmark/pull/271.

overall perf looks quite good. "select row" is a bit of an outlier. i also noticed that swap rows appears to touch every node in between.

**Comment by johan-gorter** [comment] 2017-11-02 15:15
I can confirm that maquette does not reuse DOM nodes when swapping, but it can still [animate a swap](http://johan-gorter.github.io/maquette-demo-hero/). A long in-depth discussion about this can be found here: https://github.com/AFASSoftware/maquette/issues/13.

**Comment by johan-gorter** [comment] 2017-11-02 15:17
A non-keyed implementation is not allowed in maquette, this is maquette's [rule#2](https://maquettejs.org/docs/rules.html)

**Comment by johan-gorter** [comment] 2017-11-02 15:29
Question: maquette's `projector` uses requestAnimationFrame to delay rendering to make sure it never renders more than 60 frames per second. I see that the benchmark uses the `projector`, so how can you measure how long the rendering took exactly?

**Comment by johan-gorter** [comment] 2017-11-08 22:05
Hello,

I finally had a chance to run the benchmark locally. It looks like using requestAnimationFrame or not is not affecting the outcome significantly. This means that the benchmark does a good job at approximating real world usage!

About the 'outlier' select-row. Maquette does something inefficient when handling events, because it navigates through the real dom and virtual dom to find the right event handler to invoke. In our experience this inefficiency always takes under a millisecond, so it should not be noticeable. I expect this gets enlarged somehow by this benchmark, although I do not yet see how. The benchmark outcome suggests maquette takes about 36ms to respond to the click but when I profile locally, it is usually about 13ms. (assuming 1000 rows)

I hope this pull request gets merged, so we have a baseline that we can check regularly.

By the way, I somehow had to disable uglify in build.js, because it created errors at runtime (getProjection was undefined).

**Comment by krausest** [comment] 2017-11-13 20:51
Fixed in 6d33ecfcb1346bb4e25c52012edde911bb12851e
Glad to see that a keyed framework is added!

**Closed by krausest** 2017-11-13 20:51 UTC
